# Generated by Django 5.1.3 on 2024-12-07 20:50

import campeonato.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cam', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('premio_economico', models.PositiveIntegerField(validators=[campeonato.models.validar_numero_positivo])),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_eq', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(validators=[campeonato.models.validar_texto])),
                ('apellido', models.TextField(validators=[campeonato.models.validar_texto])),
                ('fecha_nac', models.DateField()),
                ('posicion_juego', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='campeonato.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='campeonato.campeonato')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='campeonato.jugador')),
            ],
            options={
                'unique_together': {('jugador', 'campeonato')},
            },
        ),
    ]
