# Generated by Django 5.1.3 on 2024-12-07 23:39

import campeonato.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='celular',
            field=models.CharField(default='00000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='premio_economico',
            field=models.IntegerField(validators=[campeonato.models.validar_numero_positivo]),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(max_length=100, validators=[campeonato.models.validar_texto]),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='fecha_nac',
            field=models.DateField(validators=[campeonato.models.validar_fechanaci]),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=100, validators=[campeonato.models.validar_texto]),
        ),
    ]
